{
  "openapi" : "3.1.0",
  "info" : {
    "title" : "p4pa-pagopa-payments",
    "description" : "Api and Models",
    "version" : "0.0.1"
  },
  "servers" : [ {
    "url" : "http://localhost",
    "description" : "Generated server url"
  } ],
  "security" : [ {
    "BearerAuth" : [ ]
  } ],
  "tags" : [ {
    "name" : "print-payment-notice",
    "description" : "the print-payment-notice API"
  }, {
    "name" : "aca",
    "description" : "the aca API"
  }, {
    "name" : "OrgForNode",
    "description" : "the OrgForNode API"
  }, {
    "name" : "gpd",
    "description" : "the gpd API"
  }, {
    "name" : "payments-reporting",
    "description" : "the payments-reporting API"
  }, {
    "name" : "taxonomies",
    "description" : "the taxonomies API"
  } ],
  "paths" : {
    "/printpaymentnotice/generate" : {
      "post" : {
        "tags" : [ "print-payment-notice" ],
        "operationId" : "generateNotice",
        "parameters" : [ {
          "name" : "iuv",
          "in" : "query",
          "required" : true,
          "schema" : {
            "type" : "string"
          }
        } ],
        "requestBody" : {
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/DebtPositionDTO"
              }
            }
          },
          "required" : true
        },
        "responses" : {
          "404" : {
            "description" : "Not Found",
            "content" : {
              "*/*" : {
                "schema" : {
                  "$ref" : "#/components/schemas/PagoPaPaymentsErrorDTO"
                }
              }
            }
          },
          "200" : {
            "description" : "Ok",
            "content" : {
              "application/octet-stream" : {
                "schema" : {
                  "type" : "string",
                  "format" : "binary"
                }
              }
            }
          },
          "204" : {
            "description" : "No content",
            "content" : {
              "application/octet-stream" : {
                "schema" : {
                  "type" : "string",
                  "format" : "binary"
                }
              }
            }
          },
          "400" : {
            "description" : "Invalid request",
            "content" : {
              "application/octet-stream" : {
                "schema" : {
                  "type" : "string",
                  "format" : "binary"
                }
              }
            }
          },
          "500" : {
            "description" : "Internal server error",
            "content" : {
              "application/octet-stream" : {
                "schema" : {
                  "type" : "string",
                  "format" : "binary"
                }
              }
            }
          }
        },
        "security" : [ {
          "BearerAuth" : [ ]
        } ]
      }
    },
    "/printpaymentnotice/generateMassive" : {
      "post" : {
        "tags" : [ "print-payment-notice" ],
        "operationId" : "generateMassive",
        "requestBody" : {
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/NoticeRequestMassiveDTO"
              }
            }
          },
          "required" : true
        },
        "responses" : {
          "404" : {
            "description" : "Not Found",
            "content" : {
              "*/*" : {
                "schema" : {
                  "$ref" : "#/components/schemas/PagoPaPaymentsErrorDTO"
                }
              }
            }
          },
          "200" : {
            "description" : "Ok",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/GeneratedNoticeMassiveFolderDTO"
                }
              }
            }
          },
          "400" : {
            "description" : "Invalid request",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/GeneratedNoticeMassiveFolderDTO"
                }
              }
            }
          },
          "500" : {
            "description" : "Internal server error",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/GeneratedNoticeMassiveFolderDTO"
                }
              }
            }
          }
        },
        "security" : [ {
          "BearerAuth" : [ ]
        } ]
      }
    },
    "/org-for-node/service/v1/payment-options/organizations/{organization-fiscal-code}/notices/{notice-number}" : {
      "post" : {
        "tags" : [ "OrgForNode" ],
        "summary" : "Get payment options by noticeNumber",
        "description" : "Returns payment options for a given notice and organization",
        "operationId" : "getPaymentOptionsByNoticeNumber",
        "parameters" : [ {
          "name" : "notice-number",
          "in" : "path",
          "required" : true,
          "schema" : {
            "type" : "string"
          }
        }, {
          "name" : "organization-fiscal-code",
          "in" : "path",
          "required" : true,
          "schema" : {
            "type" : "string"
          }
        } ],
        "responses" : {
          "404" : {
            "description" : "Default app exception for status 404",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/ErrorResponseForNode"
                },
                "example" : {
                  "httpStatusCode" : 404,
                  "httpStatusDescription" : "Not Found",
                  "appErrorCode" : "ODP-107",
                  "timestamp" : 1724425035,
                  "dateTime" : "2024-08-23T14:57:15.635528",
                  "errorMessage" : "PAA_PAGAMENTO_SCONOSCIUTO Errore per pagamento sconosciuto"
                }
              }
            }
          },
          "500" : {
            "description" : "Internal Server Error",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/ErrorResponseForNode"
                },
                "example" : {
                  "httpStatusCode" : 500,
                  "httpStatusDescription" : "Internal Server Error",
                  "appErrorCode" : "ODP-103",
                  "timestamp" : 1724425035,
                  "dateTime" : "2024-08-23T14:57:15.635528",
                  "errorMessage" : "PAA_SYSTEM_ERROR Errore generico"
                }
              }
            }
          },
          "400" : {
            "description" : "Default app exception for status 400",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/ErrorResponseForNode"
                },
                "example" : {
                  "httpStatusCode" : 400,
                  "httpStatusDescription" : "Bad Request",
                  "appErrorCode" : "ODP-101",
                  "timestamp" : 1724425035,
                  "dateTime" : "2024-08-23T14:57:15.635528",
                  "errorMessage" : "PAA_SINTASSI Errore di sintassi del modello nella richiesta"
                }
              }
            }
          },
          "409" : {
            "description" : "Default app exception for status 409",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/ErrorResponseForNode"
                },
                "example" : {
                  "httpStatusCode" : 409,
                  "httpStatusDescription" : "Conflict",
                  "appErrorCode" : "ODP-108",
                  "timestamp" : 1724425035,
                  "dateTime" : "2024-08-23T14:57:15.635528",
                  "errorMessage" : "PAA_PAGAMENTO_DUPLICATO Errore per pagamento duplicato"
                }
              }
            }
          },
          "422" : {
            "description" : "Default app exception for status 422",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/ErrorResponseForNode"
                },
                "example" : {
                  "httpStatusCode" : 422,
                  "httpStatusDescription" : "Unprocessable Entity",
                  "appErrorCode" : "ODP-110",
                  "timestamp" : 1724425035,
                  "dateTime" : "2024-08-23T14:57:15.635528",
                  "errorMessage" : "PAA_PAGAMENTO_SCADUTO Errore per pagamento scaduto"
                }
              }
            }
          },
          "200" : {
            "description" : "Success",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/PaymentOptionsResponseForNode"
                }
              }
            }
          }
        }
      }
    },
    "/gpd/sync" : {
      "post" : {
        "tags" : [ "gpd" ],
        "operationId" : "syncGpd",
        "parameters" : [ {
          "name" : "iud",
          "in" : "query",
          "description" : "iud of installment to sync with GPD",
          "required" : true,
          "schema" : {
            "type" : "string"
          }
        } ],
        "requestBody" : {
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/DebtPositionDTO"
              }
            }
          },
          "required" : true
        },
        "responses" : {
          "404" : {
            "description" : "Not Found",
            "content" : {
              "*/*" : {
                "schema" : {
                  "$ref" : "#/components/schemas/PagoPaPaymentsErrorDTO"
                }
              }
            }
          },
          "204" : {
            "description" : "No content"
          },
          "400" : {
            "description" : "Invalid request"
          },
          "500" : {
            "description" : "Internal server error"
          }
        },
        "security" : [ {
          "BearerAuth" : [ ]
        } ]
      }
    },
    "/aca/sync" : {
      "post" : {
        "tags" : [ "aca" ],
        "operationId" : "syncAca",
        "parameters" : [ {
          "name" : "iud",
          "in" : "query",
          "description" : "iud of installment to sync with ACA",
          "required" : true,
          "schema" : {
            "type" : "string"
          }
        } ],
        "requestBody" : {
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/DebtPositionDTO"
              }
            }
          },
          "required" : true
        },
        "responses" : {
          "404" : {
            "description" : "Not Found",
            "content" : {
              "*/*" : {
                "schema" : {
                  "$ref" : "#/components/schemas/PagoPaPaymentsErrorDTO"
                }
              }
            }
          },
          "204" : {
            "description" : "No content"
          },
          "400" : {
            "description" : "Invalid request"
          },
          "500" : {
            "description" : "Internal server error"
          }
        },
        "security" : [ {
          "BearerAuth" : [ ]
        } ]
      }
    },
    "/taxonomies/fetch" : {
      "get" : {
        "tags" : [ "taxonomies" ],
        "operationId" : "fetchTaxonomies",
        "responses" : {
          "404" : {
            "description" : "Not Found",
            "content" : {
              "*/*" : {
                "schema" : {
                  "$ref" : "#/components/schemas/PagoPaPaymentsErrorDTO"
                }
              }
            }
          },
          "200" : {
            "description" : "OK",
            "content" : {
              "application/json" : {
                "schema" : {
                  "type" : "array",
                  "items" : {
                    "$ref" : "#/components/schemas/TaxonomyDTO"
                  }
                }
              }
            }
          },
          "400" : {
            "description" : "Invalid request",
            "content" : {
              "application/json" : {
                "schema" : {
                  "type" : "array",
                  "items" : {
                    "$ref" : "#/components/schemas/TaxonomyDTO"
                  }
                }
              }
            }
          },
          "500" : {
            "description" : "Internal server error",
            "content" : {
              "application/json" : {
                "schema" : {
                  "type" : "array",
                  "items" : {
                    "$ref" : "#/components/schemas/TaxonomyDTO"
                  }
                }
              }
            }
          }
        },
        "security" : [ {
          "BearerAuth" : [ ]
        } ]
      }
    },
    "/printpaymentnotice/{organizationId}/{folderId}/getSignedUrl" : {
      "get" : {
        "tags" : [ "print-payment-notice" ],
        "operationId" : "getSignedUrl",
        "parameters" : [ {
          "name" : "organizationId",
          "in" : "path",
          "required" : true,
          "schema" : {
            "type" : "integer",
            "format" : "int64"
          }
        }, {
          "name" : "folderId",
          "in" : "path",
          "required" : true,
          "schema" : {
            "type" : "string"
          }
        } ],
        "responses" : {
          "404" : {
            "description" : "Not Found",
            "content" : {
              "*/*" : {
                "schema" : {
                  "$ref" : "#/components/schemas/PagoPaPaymentsErrorDTO"
                }
              }
            }
          },
          "200" : {
            "description" : "Ok",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/SignedUrlResultDTO"
                }
              }
            }
          },
          "204" : {
            "description" : "No content",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/SignedUrlResultDTO"
                }
              }
            }
          },
          "400" : {
            "description" : "Invalid request",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/SignedUrlResultDTO"
                }
              }
            }
          },
          "500" : {
            "description" : "Internal server error",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/SignedUrlResultDTO"
                }
              }
            }
          }
        },
        "security" : [ {
          "BearerAuth" : [ ]
        } ]
      }
    },
    "/paymentsReporting/soap/{organizationId}" : {
      "get" : {
        "tags" : [ "payments-reporting" ],
        "operationId" : "soapGetPaymentsReportingList",
        "parameters" : [ {
          "name" : "organizationId",
          "in" : "path",
          "required" : true,
          "schema" : {
            "type" : "integer",
            "format" : "int64"
          }
        } ],
        "responses" : {
          "404" : {
            "description" : "Not Found",
            "content" : {
              "*/*" : {
                "schema" : {
                  "$ref" : "#/components/schemas/PagoPaPaymentsErrorDTO"
                }
              }
            }
          },
          "200" : {
            "description" : "List of payments reporting",
            "content" : {
              "application/json" : {
                "schema" : {
                  "type" : "array",
                  "items" : {
                    "$ref" : "#/components/schemas/PaymentsReportingIdDTO"
                  }
                }
              }
            }
          },
          "400" : {
            "description" : "Invalid request",
            "content" : {
              "application/json" : {
                "schema" : {
                  "type" : "array",
                  "items" : {
                    "$ref" : "#/components/schemas/PaymentsReportingIdDTO"
                  }
                }
              }
            }
          },
          "500" : {
            "description" : "Internal server error",
            "content" : {
              "application/json" : {
                "schema" : {
                  "type" : "array",
                  "items" : {
                    "$ref" : "#/components/schemas/PaymentsReportingIdDTO"
                  }
                }
              }
            }
          }
        },
        "security" : [ {
          "BearerAuth" : [ ]
        } ]
      }
    },
    "/paymentsReporting/soap/{organizationId}/fetch" : {
      "get" : {
        "tags" : [ "payments-reporting" ],
        "operationId" : "soapFetchPaymentReporting",
        "parameters" : [ {
          "name" : "organizationId",
          "in" : "path",
          "required" : true,
          "schema" : {
            "type" : "integer",
            "format" : "int64"
          }
        }, {
          "name" : "flowId",
          "in" : "query",
          "required" : true,
          "schema" : {
            "type" : "string"
          }
        }, {
          "name" : "fileName",
          "in" : "query",
          "required" : true,
          "schema" : {
            "type" : "string"
          }
        } ],
        "responses" : {
          "404" : {
            "description" : "Not Found",
            "content" : {
              "*/*" : {
                "schema" : {
                  "$ref" : "#/components/schemas/PagoPaPaymentsErrorDTO"
                }
              }
            }
          },
          "200" : {
            "description" : "OK",
            "content" : {
              "text/plain" : {
                "schema" : {
                  "type" : "integer",
                  "format" : "int64"
                }
              }
            }
          },
          "400" : {
            "description" : "Invalid request",
            "content" : {
              "text/plain" : {
                "schema" : {
                  "type" : "integer",
                  "format" : "int64"
                }
              }
            }
          },
          "500" : {
            "description" : "Internal server error",
            "content" : {
              "text/plain" : {
                "schema" : {
                  "type" : "integer",
                  "format" : "int64"
                }
              }
            }
          }
        },
        "security" : [ {
          "BearerAuth" : [ ]
        } ]
      }
    },
    "/paymentsReporting/rest/{organizationId}" : {
      "get" : {
        "tags" : [ "payments-reporting" ],
        "operationId" : "restGetPaymentsReportingList",
        "parameters" : [ {
          "name" : "organizationId",
          "in" : "path",
          "required" : true,
          "schema" : {
            "type" : "integer",
            "format" : "int64"
          }
        }, {
          "name" : "latestFlowDate",
          "in" : "query",
          "required" : false,
          "schema" : {
            "type" : "string",
            "format" : "date-time"
          }
        } ],
        "responses" : {
          "404" : {
            "description" : "Not Found",
            "content" : {
              "*/*" : {
                "schema" : {
                  "$ref" : "#/components/schemas/PagoPaPaymentsErrorDTO"
                }
              }
            }
          },
          "200" : {
            "description" : "List of payments reporting",
            "content" : {
              "application/json" : {
                "schema" : {
                  "type" : "array",
                  "items" : {
                    "$ref" : "#/components/schemas/PaymentsReportingIdDTO"
                  }
                }
              }
            }
          },
          "400" : {
            "description" : "Invalid request",
            "content" : {
              "application/json" : {
                "schema" : {
                  "type" : "array",
                  "items" : {
                    "$ref" : "#/components/schemas/PaymentsReportingIdDTO"
                  }
                }
              }
            }
          },
          "500" : {
            "description" : "Internal server error",
            "content" : {
              "application/json" : {
                "schema" : {
                  "type" : "array",
                  "items" : {
                    "$ref" : "#/components/schemas/PaymentsReportingIdDTO"
                  }
                }
              }
            }
          }
        },
        "security" : [ {
          "BearerAuth" : [ ]
        } ]
      }
    },
    "/paymentsReporting/rest/{organizationId}/fetch" : {
      "get" : {
        "tags" : [ "payments-reporting" ],
        "operationId" : "restFetchPaymentReporting",
        "parameters" : [ {
          "name" : "organizationId",
          "in" : "path",
          "required" : true,
          "schema" : {
            "type" : "integer",
            "format" : "int64"
          }
        }, {
          "name" : "flowId",
          "in" : "query",
          "required" : true,
          "schema" : {
            "type" : "string"
          }
        }, {
          "name" : "fileName",
          "in" : "query",
          "required" : true,
          "schema" : {
            "type" : "string"
          }
        }, {
          "name" : "revision",
          "in" : "query",
          "required" : false,
          "schema" : {
            "type" : "integer",
            "format" : "int64"
          }
        }, {
          "name" : "pspId",
          "in" : "query",
          "required" : false,
          "schema" : {
            "type" : "string"
          }
        } ],
        "responses" : {
          "404" : {
            "description" : "Not Found",
            "content" : {
              "*/*" : {
                "schema" : {
                  "$ref" : "#/components/schemas/PagoPaPaymentsErrorDTO"
                }
              }
            }
          },
          "200" : {
            "description" : "OK",
            "content" : {
              "text/plain" : {
                "schema" : {
                  "type" : "integer",
                  "format" : "int64"
                }
              }
            }
          },
          "400" : {
            "description" : "Invalid request",
            "content" : {
              "text/plain" : {
                "schema" : {
                  "type" : "integer",
                  "format" : "int64"
                }
              }
            }
          },
          "500" : {
            "description" : "Internal server error",
            "content" : {
              "text/plain" : {
                "schema" : {
                  "type" : "integer",
                  "format" : "int64"
                }
              }
            }
          }
        },
        "security" : [ {
          "BearerAuth" : [ ]
        } ]
      }
    }
  },
  "components" : {
    "schemas" : {
      "CategoryEnum" : {
        "type" : "string",
        "enum" : [ "PAGOPA_PAYMENTS_NOT_FOUND", "PAGOPA_PAYMENTS_BAD_REQUEST", "PAGOPA_PAYMENTS_GENERIC_ERROR", "PAGOPA_PAYMENTS_NOT_PAYABLE", "PAGOPA_PAYMENTS_CONFLICT" ]
      },
      "PagoPaPaymentsErrorDTO" : {
        "type" : "object",
        "properties" : {
          "category" : {
            "$ref" : "#/components/schemas/CategoryEnum"
          },
          "message" : {
            "type" : "string"
          },
          "traceId" : {
            "type" : "string"
          }
        },
        "required" : [ "category", "message" ]
      },
      "Action" : {
        "type" : "string",
        "enum" : [ "I", "M", "A" ]
      },
      "DebtPositionDTO" : {
        "type" : "object",
        "properties" : {
          "debtPositionId" : {
            "type" : "integer",
            "format" : "int64"
          },
          "iupdOrg" : {
            "type" : "string"
          },
          "description" : {
            "type" : "string"
          },
          "status" : {
            "$ref" : "#/components/schemas/DebtPositionStatus"
          },
          "debtPositionOrigin" : {
            "$ref" : "#/components/schemas/DebtPositionOrigin"
          },
          "organizationId" : {
            "type" : "integer",
            "format" : "int64"
          },
          "debtPositionTypeOrgId" : {
            "type" : "integer",
            "format" : "int64"
          },
          "validityDate" : {
            "type" : "string",
            "format" : "date"
          },
          "multiDebtor" : {
            "type" : "boolean"
          },
          "flagPuPagoPaPayment" : {
            "type" : "boolean"
          },
          "creationDate" : {
            "type" : "string",
            "format" : "date-time"
          },
          "updateDate" : {
            "type" : "string",
            "format" : "date-time"
          },
          "updateOperatorExternalId" : {
            "type" : "string"
          },
          "updateTraceId" : {
            "type" : "string"
          },
          "paymentOptions" : {
            "type" : "array",
            "items" : {
              "$ref" : "#/components/schemas/PaymentOptionDTO"
            }
          }
        },
        "required" : [ "debtPositionOrigin", "debtPositionTypeOrgId", "flagPuPagoPaPayment", "organizationId", "paymentOptions" ]
      },
      "DebtPositionOrigin" : {
        "type" : "string",
        "enum" : [ "ORDINARY", "ORDINARY_SIL", "SPONTANEOUS", "SPONTANEOUS_SIL", "SPONTANEOUS_MIXED", "SPONTANEOUS_PSP", "SECONDARY_ORG", "RECEIPT_FILE", "RECEIPT_PAGOPA", "REPORTING_PAGOPA" ]
      },
      "DebtPositionStatus" : {
        "type" : "string",
        "enum" : [ "TO_SYNC", "REPORTED", "PAID", "PARTIALLY_PAID", "CANCELLED", "EXPIRED", "UNPAID", "DRAFT" ]
      },
      "InstallmentDTO" : {
        "type" : "object",
        "properties" : {
          "installmentId" : {
            "type" : "integer",
            "format" : "int64"
          },
          "paymentOptionId" : {
            "type" : "integer",
            "format" : "int64"
          },
          "status" : {
            "$ref" : "#/components/schemas/InstallmentStatus"
          },
          "syncStatus" : {
            "$ref" : "#/components/schemas/InstallmentSyncStatus"
          },
          "iupdPagopa" : {
            "type" : "string"
          },
          "generateNotice" : {
            "type" : "boolean"
          },
          "iud" : {
            "type" : "string"
          },
          "iuv" : {
            "type" : "string"
          },
          "iur" : {
            "type" : "string"
          },
          "iuf" : {
            "type" : "string"
          },
          "nav" : {
            "type" : "string"
          },
          "iun" : {
            "type" : "string"
          },
          "dueDate" : {
            "type" : "string",
            "format" : "date"
          },
          "switchToExpired" : {
            "type" : "boolean"
          },
          "notificationFeeCents" : {
            "type" : "integer",
            "format" : "int64"
          },
          "amountCents" : {
            "type" : "integer",
            "format" : "int64"
          },
          "remittanceInformation" : {
            "type" : "string"
          },
          "balance" : {
            "type" : "string"
          },
          "legacyPaymentMetadata" : {
            "type" : "string"
          },
          "debtor" : {
            "$ref" : "#/components/schemas/PersonDTO"
          },
          "transfers" : {
            "type" : "array",
            "items" : {
              "$ref" : "#/components/schemas/TransferDTO"
            }
          },
          "notificationDate" : {
            "type" : "string",
            "format" : "date-time"
          },
          "ingestionFlowFileId" : {
            "type" : "integer",
            "format" : "int64"
          },
          "ingestionFlowFileLineNumber" : {
            "type" : "integer",
            "format" : "int64"
          },
          "ingestionFlowFileAction" : {
            "$ref" : "#/components/schemas/Action"
          },
          "sourceFlowName" : {
            "type" : "string"
          },
          "receiptId" : {
            "type" : "integer",
            "format" : "int64"
          },
          "creationDate" : {
            "type" : "string",
            "format" : "date-time"
          },
          "updateDate" : {
            "type" : "string",
            "format" : "date-time"
          },
          "updateOperatorExternalId" : {
            "type" : "string"
          },
          "updateTraceId" : {
            "type" : "string"
          },
          "originalRemittanceInformation" : {
            "type" : "string"
          }
        },
        "required" : [ "amountCents", "debtor", "remittanceInformation" ]
      },
      "InstallmentStatus" : {
        "type" : "string",
        "enum" : [ "TO_SYNC", "REPORTED", "PAID", "CANCELLED", "INVALID", "EXPIRED", "UNPAID", "UNPAYABLE", "DRAFT" ]
      },
      "InstallmentSyncStatus" : {
        "type" : "object",
        "properties" : {
          "syncStatusFrom" : {
            "$ref" : "#/components/schemas/InstallmentStatus"
          },
          "syncStatusTo" : {
            "$ref" : "#/components/schemas/InstallmentStatus"
          },
          "syncError" : {
            "type" : "string"
          }
        },
        "required" : [ "syncStatusFrom", "syncStatusTo" ]
      },
      "PaymentOptionDTO" : {
        "type" : "object",
        "properties" : {
          "paymentOptionId" : {
            "type" : "integer",
            "format" : "int64"
          },
          "debtPositionId" : {
            "type" : "integer",
            "format" : "int64"
          },
          "totalAmountCents" : {
            "type" : "integer",
            "format" : "int64"
          },
          "status" : {
            "$ref" : "#/components/schemas/PaymentOptionStatus"
          },
          "description" : {
            "type" : "string"
          },
          "paymentOptionType" : {
            "$ref" : "#/components/schemas/PaymentOptionType"
          },
          "paymentOptionIndex" : {
            "type" : "integer",
            "format" : "int32"
          },
          "creationDate" : {
            "type" : "string",
            "format" : "date-time"
          },
          "updateDate" : {
            "type" : "string",
            "format" : "date-time"
          },
          "updateOperatorExternalId" : {
            "type" : "string"
          },
          "updateTraceId" : {
            "type" : "string"
          },
          "installments" : {
            "type" : "array",
            "items" : {
              "$ref" : "#/components/schemas/InstallmentDTO"
            }
          }
        },
        "required" : [ "installments", "paymentOptionType", "totalAmountCents" ]
      },
      "PaymentOptionStatus" : {
        "type" : "string",
        "enum" : [ "TO_SYNC", "REPORTED", "PAID", "PARTIALLY_PAID", "CANCELLED", "INVALID", "EXPIRED", "UNPAID", "UNPAYABLE", "DRAFT" ]
      },
      "PaymentOptionType" : {
        "type" : "string",
        "enum" : [ "SINGLE_INSTALLMENT", "INSTALLMENTS", "DOWN_PAYMENT", "REDUCED_SINGLE_INSTALLMENT" ]
      },
      "PersonDTO" : {
        "type" : "object",
        "properties" : {
          "entityType" : {
            "$ref" : "#/components/schemas/PersonEntityType"
          },
          "fiscalCode" : {
            "type" : "string"
          },
          "fullName" : {
            "type" : "string"
          },
          "address" : {
            "type" : "string"
          },
          "civic" : {
            "type" : "string"
          },
          "postalCode" : {
            "type" : "string"
          },
          "location" : {
            "type" : "string"
          },
          "province" : {
            "type" : "string"
          },
          "nation" : {
            "type" : "string"
          },
          "email" : {
            "type" : "string"
          }
        },
        "required" : [ "entityType", "fiscalCode", "fullName" ]
      },
      "PersonEntityType" : {
        "type" : "string",
        "enum" : [ "F", "G" ]
      },
      "TransferDTO" : {
        "type" : "object",
        "properties" : {
          "transferId" : {
            "type" : "integer",
            "format" : "int64"
          },
          "installmentId" : {
            "type" : "integer",
            "format" : "int64"
          },
          "orgFiscalCode" : {
            "type" : "string"
          },
          "orgName" : {
            "type" : "string"
          },
          "amountCents" : {
            "type" : "integer",
            "format" : "int64"
          },
          "remittanceInformation" : {
            "type" : "string"
          },
          "stampType" : {
            "type" : "string"
          },
          "stampHashDocument" : {
            "type" : "string"
          },
          "stampProvincialResidence" : {
            "type" : "string"
          },
          "iban" : {
            "type" : "string"
          },
          "postalIban" : {
            "type" : "string"
          },
          "category" : {
            "type" : "string"
          },
          "transferIndex" : {
            "type" : "integer",
            "format" : "int32"
          },
          "creationDate" : {
            "type" : "string",
            "format" : "date-time"
          },
          "updateDate" : {
            "type" : "string",
            "format" : "date-time"
          },
          "updateOperatorExternalId" : {
            "type" : "string"
          },
          "updateTraceId" : {
            "type" : "string"
          },
          "mbdAttachment" : {
            "type" : "string"
          },
          "flagOwner" : {
            "type" : "boolean"
          }
        },
        "required" : [ "amountCents", "category", "orgFiscalCode", "orgName", "remittanceInformation", "transferIndex" ]
      },
      "GeneratedNoticeMassiveFolderDTO" : {
        "type" : "object",
        "properties" : {
          "folderId" : {
            "type" : "string"
          }
        },
        "required" : [ "folderId" ]
      },
      "NoticeRequestMassiveDTO" : {
        "type" : "object",
        "properties" : {
          "debtPositions" : {
            "type" : "array",
            "items" : {
              "$ref" : "#/components/schemas/DebtPositionDTO"
            }
          },
          "iuvList" : {
            "type" : "array",
            "items" : {
              "type" : "string"
            }
          },
          "requestId" : {
            "type" : "string"
          }
        },
        "required" : [ "debtPositions", "requestId" ]
      },
      "ErrorResponseForNode" : {
        "type" : "object",
        "properties" : {
          "httpStatusCode" : {
            "type" : "integer",
            "format" : "int32",
            "example" : 500
          },
          "httpStatusDescription" : {
            "type" : "string",
            "example" : "Internal Server Error  (HTTP Status Code reference according to https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Status)"
          },
          "errorMessage" : {
            "type" : "string",
            "example" : "An unexpected error has occurred. Please contact support."
          },
          "appErrorCode" : {
            "type" : "string",
            "example" : "ODP-<ERR_ID>"
          },
          "timestamp" : {
            "type" : "integer",
            "format" : "int64",
            "example" : 1724425035
          },
          "dateTime" : {
            "type" : "string",
            "example" : "2024-08-23T14:57:15.635528"
          }
        }
      },
      "EnumInstallmentForNode" : {
        "type" : "string",
        "enum" : [ "POI_UNPAID", "POI_PAID", "POI_EXPIRED_NOT_PAYABLE", "POI_EXPIRED_UNPAID", "POI_INVALID" ]
      },
      "EnumPoForNode" : {
        "type" : "string",
        "enum" : [ "PO_UNPAID", "PO_PAID", "PO_PARTIALLY_PAID", "PO_EXPIRED_NOT_PAYABLE", "PO_EXPIRED_UNPAID", "PO_INVALID" ]
      },
      "InstallmentForNode" : {
        "type" : "object",
        "properties" : {
          "nav" : {
            "type" : "string"
          },
          "iuv" : {
            "type" : "string"
          },
          "amount" : {
            "type" : "integer",
            "format" : "int64"
          },
          "description" : {
            "type" : "string"
          },
          "dueDate" : {
            "type" : "string"
          },
          "validFrom" : {
            "type" : "string"
          },
          "status" : {
            "$ref" : "#/components/schemas/EnumInstallmentForNode"
          },
          "statusReason" : {
            "type" : "string"
          }
        }
      },
      "PaymentOptionForNode" : {
        "type" : "object",
        "properties" : {
          "description" : {
            "type" : "string"
          },
          "numberOfInstallments" : {
            "type" : "integer",
            "format" : "int32"
          },
          "dueDate" : {
            "type" : "string"
          },
          "validFrom" : {
            "type" : "string"
          },
          "amount" : {
            "type" : "integer",
            "format" : "int64"
          },
          "status" : {
            "$ref" : "#/components/schemas/EnumPoForNode"
          },
          "statusReason" : {
            "type" : "string"
          },
          "allCCP" : {
            "type" : "boolean"
          },
          "installments" : {
            "type" : "array",
            "items" : {
              "$ref" : "#/components/schemas/InstallmentForNode"
            }
          }
        }
      },
      "PaymentOptionsResponseForNode" : {
        "type" : "object",
        "properties" : {
          "organizationFiscalCode" : {
            "type" : "string"
          },
          "companyName" : {
            "type" : "string"
          },
          "officeName" : {
            "type" : "string"
          },
          "standin" : {
            "type" : "boolean"
          },
          "paymentOptions" : {
            "type" : "array",
            "items" : {
              "$ref" : "#/components/schemas/PaymentOptionForNode"
            }
          }
        }
      },
      "TaxonomyDTO" : {
        "type" : "object",
        "properties" : {
          "organizationType" : {
            "type" : "string"
          },
          "organizationTypeDescription" : {
            "type" : "string"
          },
          "macroAreaCode" : {
            "type" : "string"
          },
          "macroAreaName" : {
            "type" : "string"
          },
          "macroAreaDescription" : {
            "type" : "string"
          },
          "serviceTypeCode" : {
            "type" : "string"
          },
          "serviceType" : {
            "type" : "string"
          },
          "serviceTypeDescription" : {
            "type" : "string"
          },
          "collectionReason" : {
            "type" : "string"
          },
          "startDateValidity" : {
            "type" : "string",
            "format" : "date-time"
          },
          "endDateOfValidity" : {
            "type" : "string",
            "format" : "date-time"
          },
          "taxonomyCode" : {
            "type" : "string"
          },
          "version" : {
            "type" : "string"
          }
        }
      },
      "SignedUrlResultDTO" : {
        "type" : "object",
        "properties" : {
          "noticesInError" : {
            "type" : "array",
            "items" : {
              "type" : "string"
            }
          },
          "processedNotices" : {
            "type" : "array",
            "items" : {
              "type" : "string"
            }
          },
          "signedUrl" : {
            "type" : "string"
          }
        }
      },
      "PaymentsReportingIdDTO" : {
        "type" : "object",
        "properties" : {
          "pagopaPaymentsReportingId" : {
            "type" : "string"
          },
          "flowDateTime" : {
            "type" : "string",
            "format" : "date-time"
          },
          "paymentsReportingFileName" : {
            "type" : "string"
          },
          "revision" : {
            "type" : "integer",
            "format" : "int32"
          },
          "pspId" : {
            "type" : "string"
          }
        },
        "required" : [ "flowDateTime", "pagopaPaymentsReportingId", "paymentsReportingFileName" ]
      }
    },
    "securitySchemes" : {
      "BearerAuth" : {
        "type" : "http",
        "scheme" : "bearer",
        "bearerFormat" : "JWT"
      }
    }
  }
}